"""
AoE2: Definitive Edition Unit Specifications, Combat Stats, Armor Classes, and Attack Bonuses.
"""

from typing import Dict, List, Optional, Tuple
from pydantic import BaseModel, Field
from aoe2_coach.schemas.game_constants import Age
from aoe2_coach.rules.armor_classes import ArmorClass


class ResourceCost(BaseModel):
    food: int = 0
    wood: int = 0
    gold: int = 0
    stone: int = 0

    @property
    def total(self) -> int:
        return self.food + self.wood + self.gold + self.stone


class UnitStats(BaseModel):
    id: str
    name: str
    age: Age
    category: str  # "infantry", "cavalry", "archer", "siege", "monk", "navy", "economy"
    train_building: str
    train_time_sec: float
    cost: ResourceCost
    hp: int
    base_attack: int
    attack_type: ArmorClass = ArmorClass.MELEE
    base_armor_melee: int = 0
    base_armor_pierce: int = 0
    attack_bonuses: Dict[ArmorClass, int] = Field(default_factory=dict)
    armor_classes: Dict[ArmorClass, int] = Field(default_factory=dict)
    range: float = 0.0
    min_range: float = 0.0
    reload_time: float = 2.0  # seconds between attacks
    speed: float = 1.0  # tiles per second
    line_of_sight: float = 4.0
    accuracy: float = 1.0  # 1.0 = 100%
    blast_radius: float = 0.0
    upgrades_to: Optional[str] = None
    upgrades_from: Optional[str] = None
    is_unique: bool = False
    civ: Optional[str] = None


# Comprehensive Unit Catalog
UNITS_DATABASE: Dict[str, UnitStats] = {
    # -------------------------------------------------------------
    # Economy & Base
    # -------------------------------------------------------------
    "villager": UnitStats(
        id="villager",
        name="Villager",
        age=Age.DARK,
        category="economy",
        train_building="town_center",
        train_time_sec=25.0,
        cost=ResourceCost(food=50),
        hp=25,
        base_attack=3,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.BUILDING: 3, ArmorClass.WALL_GATE: 3},
        armor_classes={},
        range=0.0,
        reload_time=2.03,
        speed=0.8,
        line_of_sight=4.0,
    ),
    # -------------------------------------------------------------
    # Barracks: Militia Line
    # -------------------------------------------------------------
    "militiaman": UnitStats(
        id="militiaman",
        name="Militia",
        age=Age.DARK,
        category="infantry",
        train_building="barracks",
        train_time_sec=21.0,
        cost=ResourceCost(food=60, gold=20),
        hp=40,
        base_attack=4,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=1,
        armor_classes={ArmorClass.INFANTRY: 0},
        range=0.0,
        reload_time=2.0,
        speed=0.9,
        line_of_sight=4.0,
        upgrades_to="man_at_arms",
    ),
    "man_at_arms": UnitStats(
        id="man_at_arms",
        name="Man-at-Arms",
        age=Age.FEUDAL,
        category="infantry",
        train_building="barracks",
        train_time_sec=21.0,
        cost=ResourceCost(food=60, gold=20),
        hp=45,
        base_attack=6,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.BUILDING: 2, ArmorClass.EAGLE_WARRIOR: 2},
        armor_classes={ArmorClass.INFANTRY: 0},
        range=0.0,
        reload_time=2.0,
        speed=0.9,
        line_of_sight=4.0,
        upgrades_from="militiaman",
        upgrades_to="long_swordsman",
    ),
    "long_swordsman": UnitStats(
        id="long_swordsman",
        name="Long Swordsman",
        age=Age.CASTLE,
        category="infantry",
        train_building="barracks",
        train_time_sec=21.0,
        cost=ResourceCost(food=60, gold=20),
        hp=60,
        base_attack=9,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.BUILDING: 3, ArmorClass.EAGLE_WARRIOR: 6},
        armor_classes={ArmorClass.INFANTRY: 0},
        range=0.0,
        reload_time=2.0,
        speed=0.9,
        line_of_sight=4.0,
        upgrades_from="man_at_arms",
        upgrades_to="two_handed_swordsman",
    ),
    "two_handed_swordsman": UnitStats(
        id="two_handed_swordsman",
        name="Two-Handed Swordsman",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="barracks",
        train_time_sec=21.0,
        cost=ResourceCost(food=60, gold=20),
        hp=70,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.BUILDING: 4, ArmorClass.EAGLE_WARRIOR: 8},
        armor_classes={ArmorClass.INFANTRY: 0},
        range=0.0,
        reload_time=2.0,
        speed=0.9,
        line_of_sight=5.0,
        upgrades_from="long_swordsman",
        upgrades_to="champion",
    ),
    "champion": UnitStats(
        id="champion",
        name="Champion",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="barracks",
        train_time_sec=21.0,
        cost=ResourceCost(food=60, gold=20),
        hp=70,
        base_attack=13,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.BUILDING: 4, ArmorClass.EAGLE_WARRIOR: 8},
        armor_classes={ArmorClass.INFANTRY: 0},
        range=0.0,
        reload_time=2.0,
        speed=0.9,
        line_of_sight=5.0,
        upgrades_from="two_handed_swordsman",
    ),
    # -------------------------------------------------------------
    # Barracks: Spearman Line (Anti-Cavalry)
    # -------------------------------------------------------------
    "spearman": UnitStats(
        id="spearman",
        name="Spearman",
        age=Age.FEUDAL,
        category="infantry",
        train_building="barracks",
        train_time_sec=22.0,
        cost=ResourceCost(food=35, wood=25),
        hp=45,
        base_attack=3,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.CAVALRY: 15, ArmorClass.CAMEL: 9, ArmorClass.ELEPHANT: 15, ArmorClass.SHIP: 9},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.SPEARMAN: 0},
        range=0.0,
        reload_time=3.0,
        speed=1.0,
        line_of_sight=4.0,
        upgrades_to="pikeman",
    ),
    "pikeman": UnitStats(
        id="pikeman",
        name="Pikeman",
        age=Age.CASTLE,
        category="infantry",
        train_building="barracks",
        train_time_sec=22.0,
        cost=ResourceCost(food=35, wood=25),
        hp=55,
        base_attack=4,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.CAVALRY: 22, ArmorClass.CAMEL: 18, ArmorClass.ELEPHANT: 25, ArmorClass.SHIP: 16},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.SPEARMAN: 0},
        range=0.0,
        reload_time=3.0,
        speed=1.0,
        line_of_sight=4.0,
        upgrades_from="spearman",
        upgrades_to="halberdier",
    ),
    "halberdier": UnitStats(
        id="halberdier",
        name="Halberdier",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="barracks",
        train_time_sec=22.0,
        cost=ResourceCost(food=35, wood=25),
        hp=60,
        base_attack=6,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.CAVALRY: 32, ArmorClass.CAMEL: 26, ArmorClass.ELEPHANT: 28, ArmorClass.SHIP: 17},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.SPEARMAN: 0},
        range=0.0,
        reload_time=3.0,
        speed=1.0,
        line_of_sight=4.0,
        upgrades_from="pikeman",
    ),
    # -------------------------------------------------------------
    # Barracks: Eagle Line (Mesoamerican)
    # -------------------------------------------------------------
    "eagle_scout": UnitStats(
        id="eagle_scout",
        name="Eagle Scout",
        age=Age.FEUDAL,
        category="infantry",
        train_building="barracks",
        train_time_sec=35.0,
        cost=ResourceCost(food=20, gold=50),
        hp=50,
        base_attack=4,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.MONK: 8, ArmorClass.SIEGE: 3, ArmorClass.CAVALRY: 1, ArmorClass.CAMEL: 1},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.EAGLE_WARRIOR: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.1,
        line_of_sight=6.0,
        upgrades_to="eagle_warrior",
    ),
    "eagle_warrior": UnitStats(
        id="eagle_warrior",
        name="Eagle Warrior",
        age=Age.CASTLE,
        category="infantry",
        train_building="barracks",
        train_time_sec=35.0,
        cost=ResourceCost(food=20, gold=50),
        hp=55,
        base_attack=7,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=3,
        attack_bonuses={ArmorClass.MONK: 8, ArmorClass.SIEGE: 3, ArmorClass.CAVALRY: 3, ArmorClass.CAMEL: 2},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.EAGLE_WARRIOR: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.15,
        line_of_sight=6.0,
        upgrades_from="eagle_scout",
        upgrades_to="elite_eagle_warrior",
    ),
    "elite_eagle_warrior": UnitStats(
        id="elite_eagle_warrior",
        name="Elite Eagle Warrior",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="barracks",
        train_time_sec=20.0,
        cost=ResourceCost(food=20, gold=50),
        hp=60,
        base_attack=9,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=4,
        attack_bonuses={ArmorClass.MONK: 10, ArmorClass.SIEGE: 5, ArmorClass.CAVALRY: 4, ArmorClass.CAMEL: 3},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.EAGLE_WARRIOR: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.2,
        line_of_sight=6.0,
        upgrades_from="eagle_warrior",
    ),
    # -------------------------------------------------------------
    # Archery Range: Archer Line
    # -------------------------------------------------------------
    "archer": UnitStats(
        id="archer",
        name="Archer",
        age=Age.FEUDAL,
        category="archer",
        train_building="archery_range",
        train_time_sec=35.0,
        cost=ResourceCost(wood=25, gold=45),
        hp=30,
        base_attack=4,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 3},
        armor_classes={ArmorClass.ARCHER: 0},
        range=4.0,
        reload_time=2.0,
        speed=0.96,
        line_of_sight=6.0,
        accuracy=0.8,
        upgrades_to="crossbowman",
    ),
    "crossbowman": UnitStats(
        id="crossbowman",
        name="Crossbowman",
        age=Age.CASTLE,
        category="archer",
        train_building="archery_range",
        train_time_sec=27.0,
        cost=ResourceCost(wood=25, gold=45),
        hp=35,
        base_attack=5,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 3},
        armor_classes={ArmorClass.ARCHER: 0},
        range=5.0,
        reload_time=2.0,
        speed=0.96,
        line_of_sight=7.0,
        accuracy=0.85,
        upgrades_from="archer",
        upgrades_to="arbalester",
    ),
    "arbalester": UnitStats(
        id="arbalester",
        name="Arbalester",
        age=Age.IMPERIAL,
        category="archer",
        train_building="archery_range",
        train_time_sec=27.0,
        cost=ResourceCost(wood=25, gold=45),
        hp=40,
        base_attack=6,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 3},
        armor_classes={ArmorClass.ARCHER: 0},
        range=5.0,
        reload_time=2.0,
        speed=0.96,
        line_of_sight=7.0,
        accuracy=0.9,
        upgrades_from="crossbowman",
    ),
    # -------------------------------------------------------------
    # Archery Range: Skirmisher Line (Anti-Archer)
    # -------------------------------------------------------------
    "skirmisher": UnitStats(
        id="skirmisher",
        name="Skirmisher",
        age=Age.FEUDAL,
        category="archer",
        train_building="archery_range",
        train_time_sec=22.0,
        cost=ResourceCost(food=25, wood=35),
        hp=30,
        base_attack=2,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=3,
        attack_bonuses={ArmorClass.ARCHER: 3, ArmorClass.SPEARMAN: 3},
        armor_classes={ArmorClass.ARCHER: 0},
        range=4.0,
        min_range=1.0,
        reload_time=3.0,
        speed=0.96,
        line_of_sight=6.0,
        accuracy=0.9,
        upgrades_to="elite_skirmisher",
    ),
    "elite_skirmisher": UnitStats(
        id="elite_skirmisher",
        name="Elite Skirmisher",
        age=Age.CASTLE,
        category="archer",
        train_building="archery_range",
        train_time_sec=22.0,
        cost=ResourceCost(food=25, wood=35),
        hp=35,
        base_attack=3,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=4,
        attack_bonuses={ArmorClass.ARCHER: 4, ArmorClass.SPEARMAN: 3, ArmorClass.CAVALRY_ARCHER: 2},
        armor_classes={ArmorClass.ARCHER: 0},
        range=5.0,
        min_range=1.0,
        reload_time=3.0,
        speed=0.96,
        line_of_sight=7.0,
        accuracy=0.9,
        upgrades_from="skirmisher",
        upgrades_to="imperial_skirmisher",
    ),
    "imperial_skirmisher": UnitStats(
        id="imperial_skirmisher",
        name="Imperial Skirmisher",
        age=Age.IMPERIAL,
        category="archer",
        train_building="archery_range",
        train_time_sec=22.0,
        cost=ResourceCost(food=25, wood=35),
        hp=40,
        base_attack=4,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=4,
        attack_bonuses={ArmorClass.ARCHER: 5, ArmorClass.SPEARMAN: 3, ArmorClass.CAVALRY_ARCHER: 3},
        armor_classes={ArmorClass.ARCHER: 0},
        range=5.0,
        min_range=1.0,
        reload_time=3.0,
        speed=0.96,
        line_of_sight=7.0,
        accuracy=0.95,
        upgrades_from="elite_skirmisher",
    ),
    # -------------------------------------------------------------
    # Archery Range: Cavalry Archer Line & Gunpowder
    # -------------------------------------------------------------
    "cavalry_archer": UnitStats(
        id="cavalry_archer",
        name="Cavalry Archer",
        age=Age.CASTLE,
        category="archer",
        train_building="archery_range",
        train_time_sec=34.0,
        cost=ResourceCost(wood=40, gold=60),
        hp=50,
        base_attack=6,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.CAVALRY: 0, ArmorClass.CAVALRY_ARCHER: 0},
        range=4.0,
        reload_time=2.0,
        speed=1.4,
        line_of_sight=5.0,
        accuracy=0.5,
        upgrades_to="heavy_cavalry_archer",
    ),
    "heavy_cavalry_archer": UnitStats(
        id="heavy_cavalry_archer",
        name="Heavy Cavalry Archer",
        age=Age.IMPERIAL,
        category="archer",
        train_building="archery_range",
        train_time_sec=34.0,
        cost=ResourceCost(wood=40, gold=60),
        hp=60,
        base_attack=7,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=1,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.CAVALRY: 0, ArmorClass.CAVALRY_ARCHER: 0},
        range=4.0,
        reload_time=2.0,
        speed=1.4,
        line_of_sight=6.0,
        accuracy=0.5,
        upgrades_from="cavalry_archer",
    ),
    "hand_cannoneer": UnitStats(
        id="hand_cannoneer",
        name="Hand Cannoneer",
        age=Age.IMPERIAL,
        category="archer",
        train_building="archery_range",
        train_time_sec=34.0,
        cost=ResourceCost(food=45, gold=50),
        hp=35,
        base_attack=17,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=1,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.INFANTRY: 10, ArmorClass.SPEARMAN: 1, ArmorClass.RAM: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.GUNPOWDER: 0},
        range=7.0,
        reload_time=3.45,
        speed=0.96,
        line_of_sight=9.0,
        accuracy=0.75,
    ),
    # -------------------------------------------------------------
    # Stable: Scout Line
    # -------------------------------------------------------------
    "scout_cavalry": UnitStats(
        id="scout_cavalry",
        name="Scout Cavalry",
        age=Age.DARK,
        category="cavalry",
        train_building="stable",
        train_time_sec=30.0,
        cost=ResourceCost(food=80),
        hp=45,
        base_attack=3,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.MONK: 6},
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=2.04,
        speed=1.55,
        line_of_sight=6.0,
        upgrades_to="light_cavalry",
    ),
    "light_cavalry": UnitStats(
        id="light_cavalry",
        name="Light Cavalry",
        age=Age.CASTLE,
        category="cavalry",
        train_building="stable",
        train_time_sec=30.0,
        cost=ResourceCost(food=80),
        hp=60,
        base_attack=7,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.MONK: 10},
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.5,
        line_of_sight=8.0,
        upgrades_from="scout_cavalry",
        upgrades_to="hussar",
    ),
    "hussar": UnitStats(
        id="hussar",
        name="Hussar",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=30.0,
        cost=ResourceCost(food=80),
        hp=75,
        base_attack=7,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.MONK: 12},
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=1.9,
        speed=1.5,
        line_of_sight=10.0,
        upgrades_from="light_cavalry",
    ),
    # -------------------------------------------------------------
    # Stable: Knight Line
    # -------------------------------------------------------------
    "knight": UnitStats(
        id="knight",
        name="Knight",
        age=Age.CASTLE,
        category="cavalry",
        train_building="stable",
        train_time_sec=30.0,
        cost=ResourceCost(food=60, gold=75),
        hp=100,
        base_attack=10,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=2,
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=1.8,
        speed=1.35,
        line_of_sight=4.0,
        upgrades_to="cavalier",
    ),
    "cavalier": UnitStats(
        id="cavalier",
        name="Cavalier",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=30.0,
        cost=ResourceCost(food=60, gold=75),
        hp=120,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=2,
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=1.8,
        speed=1.35,
        line_of_sight=4.0,
        upgrades_from="knight",
        upgrades_to="paladin",
    ),
    "paladin": UnitStats(
        id="paladin",
        name="Paladin",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=30.0,
        cost=ResourceCost(food=60, gold=75),
        hp=160,
        base_attack=14,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=3,
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=1.9,
        speed=1.35,
        line_of_sight=5.0,
        upgrades_from="cavalier",
    ),
    # -------------------------------------------------------------
    # Stable: Camel Line (Anti-Cavalry)
    # -------------------------------------------------------------
    "camel_rider": UnitStats(
        id="camel_rider",
        name="Camel Rider",
        age=Age.CASTLE,
        category="cavalry",
        train_building="stable",
        train_time_sec=22.0,
        cost=ResourceCost(food=55, gold=60),
        hp=100,
        base_attack=6,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.CAVALRY: 9, ArmorClass.CAMEL: 5, ArmorClass.SHIP: 5},
        armor_classes={ArmorClass.CAMEL: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.45,
        line_of_sight=4.0,
        upgrades_to="heavy_camel_rider",
    ),
    "heavy_camel_rider": UnitStats(
        id="heavy_camel_rider",
        name="Heavy Camel Rider",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=22.0,
        cost=ResourceCost(food=55, gold=60),
        hp=120,
        base_attack=7,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.CAVALRY: 18, ArmorClass.CAMEL: 9, ArmorClass.SHIP: 9},
        armor_classes={ArmorClass.CAMEL: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.45,
        line_of_sight=5.0,
        upgrades_from="camel_rider",
        upgrades_to="imperial_camel_rider",
    ),
    "imperial_camel_rider": UnitStats(
        id="imperial_camel_rider",
        name="Imperial Camel Rider",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=20.0,
        cost=ResourceCost(food=55, gold=60),
        hp=140,
        base_attack=9,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.CAVALRY: 18, ArmorClass.CAMEL: 9, ArmorClass.SHIP: 9},
        armor_classes={ArmorClass.CAMEL: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.45,
        line_of_sight=6.0,
        upgrades_from="heavy_camel_rider",
        is_unique=True,
        civ="hindustanis",
    ),
    # -------------------------------------------------------------
    # Stable: Steppe Lancer & Battle Elephant
    # -------------------------------------------------------------
    "steppe_lancer": UnitStats(
        id="steppe_lancer",
        name="Steppe Lancer",
        age=Age.CASTLE,
        category="cavalry",
        train_building="stable",
        train_time_sec=24.0,
        cost=ResourceCost(food=70, gold=40),
        hp=60,
        base_attack=9,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=1,
        armor_classes={ArmorClass.CAVALRY: 0},
        range=1.0,
        reload_time=2.3,
        speed=1.45,
        line_of_sight=4.0,
        upgrades_to="elite_steppe_lancer",
    ),
    "elite_steppe_lancer": UnitStats(
        id="elite_steppe_lancer",
        name="Elite Steppe Lancer",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=20.0,
        cost=ResourceCost(food=70, gold=40),
        hp=80,
        base_attack=11,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=1,
        armor_classes={ArmorClass.CAVALRY: 0},
        range=1.0,
        reload_time=2.0,
        speed=1.45,
        line_of_sight=5.0,
        upgrades_from="steppe_lancer",
    ),
    "battle_elephant": UnitStats(
        id="battle_elephant",
        name="Battle Elephant",
        age=Age.CASTLE,
        category="cavalry",
        train_building="stable",
        train_time_sec=28.0,
        cost=ResourceCost(food=110, gold=70),
        hp=250,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.BUILDING: 7, ArmorClass.WALL_GATE: 7},
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.ELEPHANT: 0},
        range=0.0,
        reload_time=2.0,
        speed=0.85,
        blast_radius=0.4,
        line_of_sight=4.0,
        upgrades_to="elite_battle_elephant",
    ),
    "elite_battle_elephant": UnitStats(
        id="elite_battle_elephant",
        name="Elite Battle Elephant",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=28.0,
        cost=ResourceCost(food=110, gold=70),
        hp=300,
        base_attack=14,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=3,
        attack_bonuses={ArmorClass.BUILDING: 10, ArmorClass.WALL_GATE: 10},
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.ELEPHANT: 0},
        range=0.0,
        reload_time=2.0,
        speed=0.85,
        blast_radius=0.4,
        line_of_sight=5.0,
        upgrades_from="battle_elephant",
    ),
    # -------------------------------------------------------------
    # Siege Workshop
    # -------------------------------------------------------------
    "battering_ram": UnitStats(
        id="battering_ram",
        name="Battering Ram",
        age=Age.CASTLE,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=36.0,
        cost=ResourceCost(wood=160, gold=75),
        hp=175,
        base_attack=2,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=-3,
        base_armor_pierce=180,
        attack_bonuses={ArmorClass.BUILDING: 125, ArmorClass.WALL_GATE: 40, ArmorClass.SIEGE: 40},
        armor_classes={ArmorClass.SIEGE: 0, ArmorClass.RAM: 0},
        range=0.0,
        reload_time=5.0,
        speed=0.5,
        line_of_sight=3.0,
        upgrades_to="capped_ram",
    ),
    "capped_ram": UnitStats(
        id="capped_ram",
        name="Capped Ram",
        age=Age.IMPERIAL,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=36.0,
        cost=ResourceCost(wood=160, gold=75),
        hp=200,
        base_attack=3,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=-3,
        base_armor_pierce=190,
        attack_bonuses={ArmorClass.BUILDING: 150, ArmorClass.WALL_GATE: 50, ArmorClass.SIEGE: 50},
        armor_classes={ArmorClass.SIEGE: 0, ArmorClass.RAM: 0},
        range=0.0,
        reload_time=5.0,
        speed=0.5,
        line_of_sight=3.0,
        upgrades_from="battering_ram",
        upgrades_to="siege_ram",
    ),
    "siege_ram": UnitStats(
        id="siege_ram",
        name="Siege Ram",
        age=Age.IMPERIAL,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=36.0,
        cost=ResourceCost(wood=160, gold=75),
        hp=270,
        base_attack=4,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=-3,
        base_armor_pierce=195,
        attack_bonuses={ArmorClass.BUILDING: 200, ArmorClass.WALL_GATE: 65, ArmorClass.SIEGE: 65},
        armor_classes={ArmorClass.SIEGE: 0, ArmorClass.RAM: 0},
        range=0.0,
        reload_time=5.0,
        speed=0.6,
        blast_radius=1.5,
        line_of_sight=3.0,
        upgrades_from="capped_ram",
    ),
    "mangonel": UnitStats(
        id="mangonel",
        name="Mangonel",
        age=Age.CASTLE,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=46.0,
        cost=ResourceCost(wood=160, gold=135),
        hp=50,
        base_attack=40,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=6,
        attack_bonuses={ArmorClass.BUILDING: 35, ArmorClass.SIEGE: 12},
        armor_classes={ArmorClass.SIEGE: 0},
        range=7.0,
        min_range=3.0,
        reload_time=6.0,
        speed=0.6,
        blast_radius=1.0,
        line_of_sight=9.0,
        upgrades_to="onager",
    ),
    "onager": UnitStats(
        id="onager",
        name="Onager",
        age=Age.IMPERIAL,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=46.0,
        cost=ResourceCost(wood=160, gold=135),
        hp=60,
        base_attack=50,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=7,
        attack_bonuses={ArmorClass.BUILDING: 45, ArmorClass.SIEGE: 12},
        armor_classes={ArmorClass.SIEGE: 0},
        range=8.0,
        min_range=3.0,
        reload_time=6.0,
        speed=0.6,
        blast_radius=1.25,
        line_of_sight=10.0,
        upgrades_from="mangonel",
        upgrades_to="siege_onager",
    ),
    "siege_onager": UnitStats(
        id="siege_onager",
        name="Siege Onager",
        age=Age.IMPERIAL,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=46.0,
        cost=ResourceCost(wood=160, gold=135),
        hp=70,
        base_attack=75,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=8,
        attack_bonuses={ArmorClass.BUILDING: 60, ArmorClass.SIEGE: 12},
        armor_classes={ArmorClass.SIEGE: 0},
        range=8.0,
        min_range=3.0,
        reload_time=6.0,
        speed=0.6,
        blast_radius=1.5,
        line_of_sight=10.0,
        upgrades_from="onager",
    ),
    "scorpion": UnitStats(
        id="scorpion",
        name="Scorpion",
        age=Age.CASTLE,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=30.0,
        cost=ResourceCost(wood=75, gold=75),
        hp=40,
        base_attack=12,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=6,
        attack_bonuses={ArmorClass.ELEPHANT: 6, ArmorClass.BUILDING: 2, ArmorClass.RAM: 1},
        armor_classes={ArmorClass.SIEGE: 0},
        range=7.0,
        min_range=2.0,
        reload_time=3.6,
        speed=0.65,
        line_of_sight=9.0,
        upgrades_to="heavy_scorpion",
    ),
    "heavy_scorpion": UnitStats(
        id="heavy_scorpion",
        name="Heavy Scorpion",
        age=Age.IMPERIAL,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=30.0,
        cost=ResourceCost(wood=75, gold=75),
        hp=50,
        base_attack=16,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=7,
        attack_bonuses={ArmorClass.ELEPHANT: 8, ArmorClass.BUILDING: 4, ArmorClass.RAM: 2},
        armor_classes={ArmorClass.SIEGE: 0},
        range=8.0,
        min_range=2.0,
        reload_time=3.6,
        speed=0.65,
        line_of_sight=10.0,
        upgrades_from="scorpion",
    ),
    "bombard_cannon": UnitStats(
        id="bombard_cannon",
        name="Bombard Cannon",
        age=Age.IMPERIAL,
        category="siege",
        train_building="siege_workshop",
        train_time_sec=56.0,
        cost=ResourceCost(wood=225, gold=225),
        hp=80,
        base_attack=40,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=5,
        attack_bonuses={ArmorClass.BUILDING: 200, ArmorClass.SIEGE: 20, ArmorClass.SHIP: 40, ArmorClass.WALL_GATE: 40},
        armor_classes={ArmorClass.SIEGE: 0, ArmorClass.GUNPOWDER: 0},
        range=12.0,
        min_range=5.0,
        reload_time=6.5,
        speed=0.7,
        line_of_sight=14.0,
    ),
    # -------------------------------------------------------------
    # Monastery & Castle Weapons
    # -------------------------------------------------------------
    "monk": UnitStats(
        id="monk",
        name="Monk",
        age=Age.CASTLE,
        category="monk",
        train_building="monastery",
        train_time_sec=51.0,
        cost=ResourceCost(gold=100),
        hp=30,
        base_attack=0,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        armor_classes={ArmorClass.MONK: 0},
        range=9.0,
        reload_time=5.5,
        speed=0.7,
        line_of_sight=11.0,
    ),
    "trebuchet": UnitStats(
        id="trebuchet",
        name="Trebuchet",
        age=Age.IMPERIAL,
        category="siege",
        train_building="castle",
        train_time_sec=50.0,
        cost=ResourceCost(wood=200, gold=200),
        hp=150,
        base_attack=200,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=2,
        base_armor_pierce=8,
        attack_bonuses={ArmorClass.BUILDING: 250, ArmorClass.CASTLE: 250},
        armor_classes={ArmorClass.SIEGE: 0},
        range=16.0,
        min_range=4.0,
        reload_time=10.0,
        speed=0.8,
        line_of_sight=19.0,
    ),
    # -------------------------------------------------------------
    # Civilization Unique Units (Sample Core Archetypes + Elite)
    # -------------------------------------------------------------
    "longbowman": UnitStats(
        id="longbowman",
        name="Longbowman",
        age=Age.CASTLE,
        category="archer",
        train_building="castle",
        train_time_sec=18.0,
        cost=ResourceCost(wood=35, gold=40),
        hp=35,
        base_attack=6,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=6.0,
        reload_time=2.0,
        speed=1.0,
        line_of_sight=8.0,
        accuracy=0.7,
        upgrades_to="elite_longbowman",
        is_unique=True,
        civ="britons",
    ),
    "elite_longbowman": UnitStats(
        id="elite_longbowman",
        name="Elite Longbowman",
        age=Age.IMPERIAL,
        category="archer",
        train_building="castle",
        train_time_sec=18.0,
        cost=ResourceCost(wood=35, gold=40),
        hp=40,
        base_attack=7,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.SPEARMAN: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=8.0,
        reload_time=2.0,
        speed=1.0,
        line_of_sight=10.0,
        accuracy=0.8,
        upgrades_from="longbowman",
        is_unique=True,
        civ="britons",
    ),
    "throwing_axeman": UnitStats(
        id="throwing_axeman",
        name="Throwing Axeman",
        age=Age.CASTLE,
        category="infantry",
        train_building="castle",
        train_time_sec=17.0,
        cost=ResourceCost(food=55, gold=25),
        hp=60,
        base_attack=7,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.BUILDING: 1, ArmorClass.EAGLE_WARRIOR: 1},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=3.0,
        reload_time=2.0,
        speed=1.0,
        line_of_sight=5.0,
        upgrades_to="elite_throwing_axeman",
        is_unique=True,
        civ="franks",
    ),
    "elite_throwing_axeman": UnitStats(
        id="elite_throwing_axeman",
        name="Elite Throwing Axeman",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="castle",
        train_time_sec=17.0,
        cost=ResourceCost(food=55, gold=25),
        hp=70,
        base_attack=8,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.BUILDING: 2, ArmorClass.EAGLE_WARRIOR: 2},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=4.0,
        reload_time=2.0,
        speed=1.0,
        line_of_sight=6.0,
        upgrades_from="throwing_axeman",
        is_unique=True,
        civ="franks",
    ),
    "huskarl": UnitStats(
        id="huskarl",
        name="Huskarl",
        age=Age.CASTLE,
        category="infantry",
        train_building="castle",
        train_time_sec=16.0,
        cost=ResourceCost(food=52, gold=26),  # Goths infantry discount
        hp=60,
        base_attack=10,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=6,
        attack_bonuses={ArmorClass.ARCHER: 6, ArmorClass.BUILDING: 2, ArmorClass.EAGLE_WARRIOR: 2},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.05,
        line_of_sight=3.0,
        upgrades_to="elite_huskarl",
        is_unique=True,
        civ="goths",
    ),
    "elite_huskarl": UnitStats(
        id="elite_huskarl",
        name="Elite Huskarl",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="castle",
        train_time_sec=16.0,
        cost=ResourceCost(food=52, gold=26),
        hp=70,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=8,
        attack_bonuses={ArmorClass.ARCHER: 10, ArmorClass.BUILDING: 3, ArmorClass.EAGLE_WARRIOR: 3},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.05,
        line_of_sight=5.0,
        upgrades_from="huskarl",
        is_unique=True,
        civ="goths",
    ),
    "cataphract": UnitStats(
        id="cataphract",
        name="Cataphract",
        age=Age.CASTLE,
        category="cavalry",
        train_building="castle",
        train_time_sec=20.0,
        cost=ResourceCost(food=70, gold=75),
        hp=110,
        base_attack=9,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.INFANTRY: 9},
        armor_classes={ArmorClass.CAVALRY: 12, ArmorClass.UNIQUE_UNIT: 0},  # Byzantine armor ignores +12 cav bonus!
        range=0.0,
        reload_time=1.8,
        speed=1.35,
        line_of_sight=4.0,
        upgrades_to="elite_cataphract",
        is_unique=True,
        civ="byzantines",
    ),
    "elite_cataphract": UnitStats(
        id="elite_cataphract",
        name="Elite Cataphract",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="castle",
        train_time_sec=20.0,
        cost=ResourceCost(food=70, gold=75),
        hp=150,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.INFANTRY: 12},
        armor_classes={ArmorClass.CAVALRY: 16, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=1.7,
        speed=1.35,
        line_of_sight=5.0,
        upgrades_from="cataphract",
        is_unique=True,
        civ="byzantines",
    ),
    "berserk": UnitStats(
        id="berserk",
        name="Berserk",
        age=Age.CASTLE,
        category="infantry",
        train_building="castle",
        train_time_sec=14.0,
        cost=ResourceCost(food=65, gold=25),
        hp=61,  # +20% Vikings HP
        base_attack=9,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.BUILDING: 2, ArmorClass.EAGLE_WARRIOR: 2, ArmorClass.CAVALRY: 0},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.05,
        line_of_sight=3.0,
        upgrades_to="elite_berserk",
        is_unique=True,
        civ="vikings",
    ),
    "elite_berserk": UnitStats(
        id="elite_berserk",
        name="Elite Berserk",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="castle",
        train_time_sec=14.0,
        cost=ResourceCost(food=65, gold=25),
        hp=75,
        base_attack=14,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.BUILDING: 3, ArmorClass.EAGLE_WARRIOR: 3, ArmorClass.CAVALRY: 0},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.05,
        line_of_sight=5.0,
        upgrades_from="berserk",
        is_unique=True,
        civ="vikings",
    ),
    "mangudai": UnitStats(
        id="mangudai",
        name="Mangudai",
        age=Age.CASTLE,
        category="archer",
        train_building="castle",
        train_time_sec=26.0,
        cost=ResourceCost(wood=55, gold=65),
        hp=60,
        base_attack=6,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SIEGE: 3, ArmorClass.SPEARMAN: 1},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.CAVALRY: 0, ArmorClass.CAVALRY_ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=4.0,
        reload_time=1.68,
        speed=1.45,
        line_of_sight=6.0,
        accuracy=0.95,
        upgrades_to="elite_mangudai",
        is_unique=True,
        civ="mongols",
    ),
    "elite_mangudai": UnitStats(
        id="elite_mangudai",
        name="Elite Mangudai",
        age=Age.IMPERIAL,
        category="archer",
        train_building="castle",
        train_time_sec=26.0,
        cost=ResourceCost(wood=55, gold=65),
        hp=60,
        base_attack=8,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=1,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SIEGE: 5, ArmorClass.SPEARMAN: 1},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.CAVALRY: 0, ArmorClass.CAVALRY_ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=4.0,
        reload_time=1.68,
        speed=1.45,
        line_of_sight=6.0,
        accuracy=0.95,
        upgrades_from="mangudai",
        is_unique=True,
        civ="mongols",
    ),
    "conquistador": UnitStats(
        id="conquistador",
        name="Conquistador",
        age=Age.CASTLE,
        category="cavalry",
        train_building="castle",
        train_time_sec=24.0,
        cost=ResourceCost(food=60, gold=70),
        hp=65,
        base_attack=16,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=2,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.SPEARMAN: 2, ArmorClass.BUILDING: 2, ArmorClass.RAM: 2},
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.GUNPOWDER: 0, ArmorClass.ARCHER: 0, ArmorClass.CAVALRY_ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=6.0,
        reload_time=2.9,
        speed=1.3,
        line_of_sight=8.0,
        accuracy=0.65,
        upgrades_to="elite_conquistador",
        is_unique=True,
        civ="spanish",
    ),
    "elite_conquistador": UnitStats(
        id="elite_conquistador",
        name="Elite Conquistador",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="castle",
        train_time_sec=24.0,
        cost=ResourceCost(food=60, gold=70),
        hp=70,
        base_attack=18,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=2,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.SPEARMAN: 2, ArmorClass.BUILDING: 2, ArmorClass.RAM: 2},
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.GUNPOWDER: 0, ArmorClass.ARCHER: 0, ArmorClass.CAVALRY_ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=6.0,
        reload_time=2.9,
        speed=1.3,
        line_of_sight=9.0,
        accuracy=0.7,
        upgrades_from="conquistador",
        is_unique=True,
        civ="spanish",
    ),
    "jaguar_warrior": UnitStats(
        id="jaguar_warrior",
        name="Jaguar Warrior",
        age=Age.CASTLE,
        category="infantry",
        train_building="castle",
        train_time_sec=17.0,
        cost=ResourceCost(food=60, gold=30),
        hp=65,
        base_attack=10,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.INFANTRY: 10, ArmorClass.EAGLE_WARRIOR: 2},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.0,
        line_of_sight=3.0,
        upgrades_to="elite_jaguar_warrior",
        is_unique=True,
        civ="aztecs",
    ),
    "elite_jaguar_warrior": UnitStats(
        id="elite_jaguar_warrior",
        name="Elite Jaguar Warrior",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="castle",
        train_time_sec=17.0,
        cost=ResourceCost(food=60, gold=30),
        hp=75,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.INFANTRY: 11, ArmorClass.EAGLE_WARRIOR: 2},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.0,
        line_of_sight=5.0,
        upgrades_from="jaguar_warrior",
        is_unique=True,
        civ="aztecs",
    ),
    "plumed_archer": UnitStats(
        id="plumed_archer",
        name="Plumed Archer",
        age=Age.CASTLE,
        category="archer",
        train_building="castle",
        train_time_sec=16.0,
        cost=ResourceCost(wood=50, gold=50),
        hp=50,
        base_attack=5,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=1,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.SPEARMAN: 2, ArmorClass.INFANTRY: 1},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=4.0,
        reload_time=1.9,
        speed=1.2,
        line_of_sight=6.0,
        accuracy=0.8,
        upgrades_to="elite_plumed_archer",
        is_unique=True,
        civ="mayans",
    ),
    "elite_plumed_archer": UnitStats(
        id="elite_plumed_archer",
        name="Elite Plumed Archer",
        age=Age.IMPERIAL,
        category="archer",
        train_building="castle",
        train_time_sec=16.0,
        cost=ResourceCost(wood=45, gold=45),
        hp=55,
        base_attack=5,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=2,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.SPEARMAN: 2, ArmorClass.INFANTRY: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=5.0,
        reload_time=1.9,
        speed=1.2,
        line_of_sight=7.0,
        accuracy=0.9,
        upgrades_from="plumed_archer",
        is_unique=True,
        civ="mayans",
    ),
    "ghulam": UnitStats(
        id="ghulam",
        name="Ghulam",
        age=Age.CASTLE,
        category="infantry",
        train_building="castle",
        train_time_sec=12.0,
        cost=ResourceCost(food=30, gold=45),
        hp=55,
        base_attack=8,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=3,
        attack_bonuses={ArmorClass.ARCHER: 3, ArmorClass.EAGLE_WARRIOR: 2},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.15,
        line_of_sight=5.0,
        upgrades_to="elite_ghulam",
        is_unique=True,
        civ="hindustanis",
    ),
    "elite_ghulam": UnitStats(
        id="elite_ghulam",
        name="Elite Ghulam",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="castle",
        train_time_sec=12.0,
        cost=ResourceCost(food=30, gold=45),
        hp=65,
        base_attack=10,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=6,
        attack_bonuses={ArmorClass.ARCHER: 5, ArmorClass.EAGLE_WARRIOR: 3},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=2.0,
        speed=1.15,
        line_of_sight=6.0,
        upgrades_from="ghulam",
        is_unique=True,
        civ="hindustanis",
    ),
    "shrivamsha_rider": UnitStats(
        id="shrivamsha_rider",
        name="Shrivamsha Rider",
        age=Age.CASTLE,
        category="cavalry",
        train_building="stable",
        train_time_sec=20.0,
        cost=ResourceCost(food=70, gold=20),
        hp=55,
        base_attack=9,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=1,
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=1.75,
        speed=1.6,
        line_of_sight=5.0,
        upgrades_to="elite_shrivamsha_rider",
        is_unique=True,
        civ="gurjaras",
    ),
    "elite_shrivamsha_rider": UnitStats(
        id="elite_shrivamsha_rider",
        name="Elite Shrivamsha Rider",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="stable",
        train_time_sec=20.0,
        cost=ResourceCost(food=70, gold=20),
        hp=70,
        base_attack=11,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=0,
        base_armor_pierce=2,
        armor_classes={ArmorClass.CAVALRY: 0},
        range=0.0,
        reload_time=1.75,
        speed=1.6,
        line_of_sight=6.0,
        upgrades_from="shrivamsha_rider",
        is_unique=True,
        civ="gurjaras",
    ),
    "chakram_thrower": UnitStats(
        id="chakram_thrower",
        name="Chakram Thrower",
        age=Age.CASTLE,
        category="infantry",
        train_building="castle",
        train_time_sec=16.0,
        cost=ResourceCost(food=65, gold=30),
        hp=50,
        base_attack=5,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=1,
        attack_bonuses={ArmorClass.INFANTRY: 2, ArmorClass.EAGLE_WARRIOR: 1},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=4.0,
        reload_time=2.0,
        speed=1.1,
        blast_radius=0.5,
        line_of_sight=6.0,
        upgrades_to="elite_chakram_thrower",
        is_unique=True,
        civ="gurjaras",
    ),
    "elite_chakram_thrower": UnitStats(
        id="elite_chakram_thrower",
        name="Elite Chakram Thrower",
        age=Age.IMPERIAL,
        category="infantry",
        train_building="castle",
        train_time_sec=16.0,
        cost=ResourceCost(food=65, gold=30),
        hp=60,
        base_attack=6,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=1,
        base_armor_pierce=2,
        attack_bonuses={ArmorClass.INFANTRY: 3, ArmorClass.EAGLE_WARRIOR: 2},
        armor_classes={ArmorClass.INFANTRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=5.0,
        reload_time=2.0,
        speed=1.1,
        blast_radius=0.5,
        line_of_sight=7.0,
        upgrades_from="chakram_thrower",
        is_unique=True,
        civ="gurjaras",
    ),
    "centurion": UnitStats(
        id="centurion",
        name="Centurion",
        age=Age.CASTLE,
        category="cavalry",
        train_building="castle",
        train_time_sec=24.0,
        cost=ResourceCost(food=75, gold=85),
        hp=110,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=3,
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=1.9,
        speed=1.35,
        line_of_sight=5.0,
        upgrades_to="elite_centurion",
        is_unique=True,
        civ="romans",
    ),
    "elite_centurion": UnitStats(
        id="elite_centurion",
        name="Elite Centurion",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="castle",
        train_time_sec=24.0,
        cost=ResourceCost(food=75, gold=85),
        hp=155,
        base_attack=15,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=3,
        base_armor_pierce=3,
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=1.9,
        speed=1.35,
        line_of_sight=6.0,
        upgrades_from="centurion",
        is_unique=True,
        civ="romans",
    ),
    "monaspa": UnitStats(
        id="monaspa",
        name="Monaspa",
        age=Age.CASTLE,
        category="cavalry",
        train_building="castle",
        train_time_sec=14.0,
        cost=ResourceCost(food=60, gold=45),
        hp=75,
        base_attack=12,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=2,
        base_armor_pierce=2,
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=1.8,
        speed=1.4,
        line_of_sight=5.0,
        upgrades_to="elite_monaspa",
        is_unique=True,
        civ="georgians",
    ),
    "elite_monaspa": UnitStats(
        id="elite_monaspa",
        name="Elite Monaspa",
        age=Age.IMPERIAL,
        category="cavalry",
        train_building="castle",
        train_time_sec=14.0,
        cost=ResourceCost(food=60, gold=45),
        hp=90,
        base_attack=14,
        attack_type=ArmorClass.MELEE,
        base_armor_melee=3,
        base_armor_pierce=2,
        armor_classes={ArmorClass.CAVALRY: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=0.0,
        reload_time=1.8,
        speed=1.4,
        line_of_sight=6.0,
        upgrades_from="monaspa",
        is_unique=True,
        civ="georgians",
    ),
    "composite_bowman": UnitStats(
        id="composite_bowman",
        name="Composite Bowman",
        age=Age.CASTLE,
        category="archer",
        train_building="archery_range",
        train_time_sec=21.0,
        cost=ResourceCost(wood=35, gold=45),
        hp=40,
        base_attack=7,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=4.0,
        reload_time=2.0,
        speed=0.96,
        line_of_sight=6.0,
        accuracy=0.85,
        upgrades_to="elite_composite_bowman",
        is_unique=True,
        civ="armenians",
    ),
    "elite_composite_bowman": UnitStats(
        id="elite_composite_bowman",
        name="Elite Composite Bowman",
        age=Age.IMPERIAL,
        category="archer",
        train_building="archery_range",
        train_time_sec=21.0,
        cost=ResourceCost(wood=35, gold=45),
        hp=45,
        base_attack=8,
        attack_type=ArmorClass.PIERCE,
        base_armor_melee=0,
        base_armor_pierce=0,
        attack_bonuses={ArmorClass.SPEARMAN: 2},
        armor_classes={ArmorClass.ARCHER: 0, ArmorClass.UNIQUE_UNIT: 0},
        range=4.0,
        reload_time=2.0,
        speed=0.96,
        line_of_sight=7.0,
        accuracy=0.9,
        upgrades_from="composite_bowman",
        is_unique=True,
        civ="armenians",
    ),
}


def get_unit_stats(unit_id: str) -> Optional[UnitStats]:
    """Retrieve unit stats by canonical identifier."""
    return UNITS_DATABASE.get(unit_id.lower())
