"""
AoE2 Curated Match Scenarios and Presets for Rapid Testing and 1-Click Loading.
"""

from typing import List
from aoe2_coach.api.schemas import PresetScenario, SnapshotInput

PRESET_SCENARIOS: List[PresetScenario] = [
    PresetScenario(
        id="franks-vs-vikings-castle",
        title="Franks vs Vikings — Castle Age Timing",
        description="Floating 750 wood while enemy masses Berserkers without pikes. Time to drop stables and flood Knights!",
        difficulty="Intermediate (950 ELO)",
        snapshot=SnapshotInput(
            player_civ="Franks",
            opponent_civ="Vikings",
            player_elo=950,
            game_time_minutes=22.5,
            current_age=3,
            food=320,
            wood=750,
            gold=120,
            stone=450,
            vills_food=14,
            vills_wood=26,
            vills_gold=6,
            vills_stone=2,
            vills_total=48,
            military_units={"Scout Cavalry": 4, "Knight": 2},
            player_buildings={"Town Center": 2, "Barracks": 1, "Stable": 1, "Blacksmith": 1},
            completed_techs=["Wheelbarrow", "Double-Bit Axe", "Horse Collar"],
            sighted_enemy_units={"Berserk": 5},
            sighted_enemy_buildings={"Castle": 1},
            user_notes="Need to punish Viking infantry before Imperial Berserkergang upgrade.",
        ),
    ),
    PresetScenario(
        id="britons-vs-mayans-xbow",
        title="Britons vs Mayans — Crossbow Range Control",
        description="Facing Mayan archers & eagle scouts in Castle Age. Leverage +1 Range and Bodkin Arrow.",
        difficulty="Intermediate (1150 ELO)",
        snapshot=SnapshotInput(
            player_civ="Britons",
            opponent_civ="Mayans",
            player_elo=1150,
            game_time_minutes=19.0,
            current_age=3,
            food=180,
            wood=340,
            gold=220,
            stone=50,
            vills_food=16,
            vills_wood=18,
            vills_gold=10,
            vills_stone=0,
            vills_total=44,
            military_units={"Crossbowman": 14},
            player_buildings={"Town Center": 2, "Archery Range": 2, "Blacksmith": 1},
            completed_techs=["Fletching", "Bodkin Arrow", "Double-Bit Axe"],
            sighted_enemy_units={"Archer": 12, "Eagle Scout": 4},
            sighted_enemy_buildings={"Archery Range": 2},
            user_notes="Out-range opponent crossbows while guarding against eagle warrior flanks.",
        ),
    ),
    PresetScenario(
        id="goths-vs-britons-flood",
        title="Goths vs Britons — Huskarl Mass",
        description="Imperial Age transition against archer-heavy Britons. Deploy pierce-immune Huskarls and siege.",
        difficulty="Advanced (1350 ELO)",
        snapshot=SnapshotInput(
            player_civ="Goths",
            opponent_civ="Britons",
            player_elo=1350,
            game_time_minutes=32.0,
            current_age=4,
            food=850,
            wood=600,
            gold=450,
            stone=200,
            vills_food=36,
            vills_wood=30,
            vills_gold=22,
            vills_stone=4,
            vills_total=92,
            military_units={"Huskarl": 18, "Champion": 10},
            player_buildings={"Town Center": 3, "Barracks": 6, "Castle": 2},
            completed_techs=["Anarchy", "Perfusion", "Ring Archer Armor", "Blast Furnace"],
            sighted_enemy_units={"Arbalester": 30, "Longbowman": 12, "Trebuchet": 2},
            sighted_enemy_buildings={"Castle": 2, "Archery Range": 4},
            user_notes="Briton arbalest mass is huge. Flood through barracks with Perfusion.",
        ),
    ),
    PresetScenario(
        id="mongols-vs-teutons-kite",
        title="Mongols vs Teutons — Mangudai Hit & Run",
        description="Teutons marching slow Heavy Cavalry and Siege Onagers. Exploit Mangudai mobility and siege bonus.",
        difficulty="Expert (1550 ELO)",
        snapshot=SnapshotInput(
            player_civ="Mongols",
            opponent_civ="Teutons",
            player_elo=1550,
            game_time_minutes=28.0,
            current_age=3,
            food=400,
            wood=550,
            gold=600,
            stone=300,
            vills_food=24,
            vills_wood=28,
            vills_gold=18,
            vills_stone=5,
            vills_total=75,
            military_units={"Mangudai": 16, "Light Cavalry": 8},
            player_buildings={"Town Center": 3, "Castle": 2, "Archery Range": 2, "Stable": 1},
            completed_techs=["Bodkin Arrow", "Thumb Ring", "Husbandry", "Bloodlines"],
            sighted_enemy_units={"Knight": 14, "Mangonel": 3},
            sighted_enemy_buildings={"Stable": 2, "Siege Workshop": 1},
            user_notes="Kite Teutonic knights and pick off mangonels before they reach TC.",
        ),
    ),
    PresetScenario(
        id="feudal-scout-rush-arabia",
        title="Magyars vs Huns — Feudal Scout Rush",
        description="Early 12-minute Feudal pressure on Arabia. Balance wood for farms while keeping 1 Stable pumping.",
        difficulty="Beginner (800 ELO)",
        snapshot=SnapshotInput(
            player_civ="Magyars",
            opponent_civ="Huns",
            player_elo=800,
            game_time_minutes=12.0,
            current_age=2,
            food=120,
            wood=240,
            gold=40,
            stone=0,
            vills_food=11,
            vills_wood=10,
            vills_gold=0,
            vills_stone=0,
            vills_total=21,
            military_units={"Scout Cavalry": 3},
            player_buildings={"Town Center": 1, "Barracks": 1, "Stable": 1},
            completed_techs=["Double-Bit Axe"],
            sighted_enemy_units={"Archer": 2},
            sighted_enemy_buildings={"Archery Range": 1},
            user_notes="Scouts are out! Attack woodlines and prevent archer mass.",
        ),
    ),
]
