"""
Age of Empires II: Definitive Edition Game Constants & Reference Mappings.
"""

from enum import IntEnum
from typing import Dict, Any, Tuple, Optional


class Age(IntEnum):
    DARK = 1
    FEUDAL = 2
    CASTLE = 3
    IMPERIAL = 4

    @classmethod
    def from_name(cls, name: str) -> "Age":
        name_lower = name.lower()
        if "dark" in name_lower:
            return cls.DARK
        elif "feudal" in name_lower:
            return cls.FEUDAL
        elif "castle" in name_lower:
            return cls.CASTLE
        elif "imperial" in name_lower or "imp" in name_lower:
            return cls.IMPERIAL
        return cls.DARK

    @property
    def display_name(self) -> str:
        names = {
            Age.DARK: "Dark Age",
            Age.FEUDAL: "Feudal Age",
            Age.CASTLE: "Castle Age",
            Age.IMPERIAL: "Imperial Age",
        }
        return names.get(self, "Unknown Age")


# Civilization ID to Name Mapping
CIVILIZATIONS: Dict[int, str] = {
    1: "Britons",
    2: "Franks",
    3: "Goths",
    4: "Teutons",
    5: "Japanese",
    6: "Chinese",
    7: "Byzantines",
    8: "Persians",
    9: "Saracens",
    10: "Turks",
    11: "Vikings",
    12: "Mongols",
    13: "Celts",
    14: "Spanish",
    15: "Aztecs",
    16: "Mayans",
    17: "Huns",
    18: "Koreans",
    19: "Italians",
    20: "Hindustanis",
    21: "Incas",
    22: "Magyars",
    23: "Slavs",
    24: "Portuguese",
    25: "Ethiopians",
    26: "Malians",
    27: "Berbers",
    28: "Khmer",
    29: "Malay",
    30: "Burmese",
    31: "Vietnamese",
    32: "Bulgarians",
    33: "Tatars",
    34: "Cumans",
    35: "Lithuanians",
    36: "Burgundians",
    37: "Sicilians",
    38: "Poles",
    39: "Bohemians",
    40: "Dravidians",
    41: "Bengalis",
    42: "Gurjaras",
    43: "Romans",
    44: "Armenians",
    45: "Georgians",
}

CIV_NAME_TO_ID: Dict[str, int] = {name.lower(): cid for cid, name in CIVILIZATIONS.items()}

# Unit Classifications
UNIT_CATEGORIES = {
    "villager": "economy",
    "scout_cavalry": "cavalry",
    "light_cavalry": "cavalry",
    "hussar": "cavalry",
    "knight": "cavalry",
    "cavalier": "cavalry",
    "paladin": "cavalry",
    "camel_rider": "cavalry",
    "heavy_camel_rider": "cavalry",
    "imperial_camel_rider": "cavalry",
    "battle_elephant": "cavalry",
    "elite_battle_elephant": "cavalry",
    "steppe_lancer": "cavalry",
    "elite_steppe_lancer": "cavalry",
    "shrivamsha_rider": "cavalry",
    "archer": "archer",
    "crossbowman": "archer",
    "arbalester": "archer",
    "skirmisher": "archer",
    "elite_skirmisher": "archer",
    "imperial_skirmisher": "archer",
    "cavalry_archer": "archer",
    "heavy_cavalry_archer": "archer",
    "hand_cannoneer": "archer",
    "militiaman": "infantry",
    "man_at_arms": "infantry",
    "long_swordsman": "infantry",
    "two_handed_swordsman": "infantry",
    "champion": "infantry",
    "spearman": "infantry",
    "pikeman": "infantry",
    "halberdier": "infantry",
    "eagle_scout": "infantry",
    "eagle_warrior": "infantry",
    "elite_eagle_warrior": "infantry",
    "battering_ram": "siege",
    "capped_ram": "siege",
    "siege_ram": "siege",
    "mangonel": "siege",
    "onager": "siege",
    "siege_onager": "siege",
    "scorpion": "siege",
    "heavy_scorpion": "siege",
    "bombard_cannon": "siege",
    "trebuchet": "siege",
    "siege_tower": "siege",
    "monk": "monk",
    "missionary": "monk",
    "galley": "navy",
    "war_galley": "navy",
    "galleon": "navy",
    "fire_galley": "navy",
    "fire_ship": "navy",
    "fast_fire_ship": "navy",
    "demolition_raft": "navy",
    "demolition_ship": "navy",
    "heavy_demolition_ship": "navy",
    "cannon_galleon": "navy",
    "elite_cannon_galleon": "navy",
    "dromon": "navy",
    "trade_cart": "economy",
    "fishing_ship": "economy",
    "transport_ship": "navy",
}

# Building Classifications
BUILDING_CATEGORIES = {
    "town_center": "economy",
    "house": "economy",
    "mill": "economy",
    "farm": "economy",
    "lumber_camp": "economy",
    "mining_camp": "economy",
    "dock": "military",
    "barracks": "military",
    "archery_range": "military",
    "stable": "military",
    "siege_workshop": "military",
    "monastery": "military",
    "market": "economy",
    "blacksmith": "technology",
    "university": "technology",
    "castle": "defense",
    "outpost": "defense",
    "watch_tower": "defense",
    "guard_tower": "defense",
    "keep": "defense",
    "bombard_tower": "defense",
    "palisade_wall": "defense",
    "palisade_gate": "defense",
    "stone_wall": "defense",
    "gate": "defense",
    "fortified_wall": "defense",
    "fish_trap": "economy",
    "wonder": "wonder",
    "feitoria": "economy",
    "folwark": "economy",
    "mule_cart": "economy",
    "caravanserai": "economy",
}

# Canonical Mapping for Object IDs (Units and Buildings)
OBJECT_ID_TO_CANONICAL: Dict[int, str] = {
    # Villagers & Eco
    83: "villager",
    118: "villager",
    128: "trade_cart",
    204: "trade_cart",
    13: "fishing_ship",
    545: "transport_ship",
    # Infantry
    74: "militiaman",
    75: "man_at_arms",
    77: "long_swordsman",
    473: "two_handed_swordsman",
    567: "champion",
    93: "spearman",
    358: "pikeman",
    359: "halberdier",
    751: "eagle_scout",
    753: "eagle_warrior",
    752: "elite_eagle_warrior",
    # Archers
    4: "archer",
    24: "crossbowman",
    492: "arbalester",
    7: "skirmisher",
    6: "elite_skirmisher",
    1155: "imperial_skirmisher",
    39: "cavalry_archer",
    474: "heavy_cavalry_archer",
    5: "hand_cannoneer",
    # Cavalry
    448: "scout_cavalry",
    546: "light_cavalry",
    441: "hussar",
    38: "knight",
    283: "cavalier",
    569: "paladin",
    329: "camel_rider",
    330: "heavy_camel_rider",
    207: "imperial_camel_rider",
    1132: "battle_elephant",
    1134: "elite_battle_elephant",
    1370: "steppe_lancer",
    1372: "elite_steppe_lancer",
    1751: "shrivamsha_rider",
    # Siege
    35: "battering_ram",
    422: "capped_ram",
    548: "siege_ram",
    280: "mangonel",
    550: "onager",
    588: "siege_onager",
    279: "scorpion",
    542: "heavy_scorpion",
    36: "bombard_cannon",
    42: "trebuchet",
    1105: "siege_tower",
    # Monks
    125: "monk",
    775: "missionary",
    # Navy
    539: "galley",
    21: "war_galley",
    442: "galleon",
    1103: "fire_galley",
    529: "fire_ship",
    532: "fast_fire_ship",
    1104: "demolition_raft",
    527: "demolition_ship",
    528: "heavy_demolition_ship",
    420: "cannon_galleon",
    691: "elite_cannon_galleon",
    1795: "dromon",
    # Unique Units
    8: "longbowman",
    530: "elite_longbowman",
    281: "throwing_axeman",
    531: "elite_throwing_axeman",
    41: "huskarl",
    555: "elite_huskarl",
    291: "teutonic_knight",
    554: "elite_teutonic_knight",
    282: "samurai",
    560: "elite_samurai",
    73: "chu_ko_nu",
    559: "elite_chu_ko_nu",
    40: "cataphract",
    553: "elite_cataphract",
    239: "war_elephant",
    558: "elite_war_elephant",
    293: "mameluke",
    556: "elite_mameluke",
    46: "janissary",
    557: "elite_janissary",
    692: "berserk",
    694: "elite_berserk",
    11: "mangudai",
    561: "elite_mangudai",
    232: "woad_raider",
    534: "elite_woad_raider",
    771: "conquistador",
    773: "elite_conquistador",
    725: "jaguar_warrior",
    726: "elite_jaguar_warrior",
    763: "plumed_archer",
    765: "elite_plumed_archer",
    755: "tarkan",
    757: "elite_tarkan",
    831: "war_wagon",
    832: "elite_war_wagon",
    866: "genoese_crossbowman",
    868: "elite_genoese_crossbowman",
    869: "condottiero",
    879: "kamayuk",
    881: "elite_kamayuk",
    876: "magyar_huszar",
    878: "elite_magyar_huszar",
    873: "boyar",
    875: "elite_boyar",
    1001: "organ_gun",
    1003: "elite_organ_gun",
    1007: "caravel",
    1009: "elite_caravel",
    1004: "shotel_warrior",
    1006: "elite_shotel_warrior",
    1013: "gbeto",
    1015: "elite_gbeto",
    1016: "camel_archer",
    1018: "elite_camel_archer",
    1079: "ballista_elephant",
    1081: "elite_ballista_elephant",
    1120: "karambit_warrior",
    1122: "elite_karambit_warrior",
    1123: "arambai",
    1125: "elite_arambai",
    1126: "rattan_archer",
    1128: "elite_rattan_archer",
    1228: "konnik",
    1230: "elite_konnik",
    1232: "keshik",
    1234: "elite_keshik",
    1258: "kipchak",
    1260: "elite_kipchak",
    1236: "leitis",
    1238: "elite_leitis",
    1655: "coustillier",
    1657: "elite_coustillier",
    1659: "serjeant",
    1661: "elite_serjeant",
    1667: "obuch",
    1669: "elite_obuch",
    1664: "hussite_wagon",
    1666: "elite_hussite_wagon",
    1735: "urumi_swordsman",
    1737: "elite_urumi_swordsman",
    1738: "ratha",
    1740: "elite_ratha",
    1741: "chakram_thrower",
    1743: "elite_chakram_thrower",
    1744: "ghulam",
    1746: "elite_ghulam",
    1796: "centurion",
    1798: "elite_centurion",
    1799: "legionary",
    1803: "composite_bowman",
    1805: "elite_composite_bowman",
    1806: "monaspa",
    1808: "elite_monaspa",
    # Buildings
    109: "town_center",
    71: "town_center",
    70: "house",
    68: "mill",
    50: "farm",
    259: "farm",
    562: "lumber_camp",
    584: "mining_camp",
    45: "dock",
    133: "dock",
    12: "barracks",
    87: "archery_range",
    101: "stable",
    49: "siege_workshop",
    30: "monastery",
    84: "market",
    103: "blacksmith",
    209: "university",
    82: "castle",
    598: "outpost",
    79: "watch_tower",
    234: "guard_tower",
    235: "keep",
    236: "bombard_tower",
    72: "palisade_wall",
    63: "palisade_gate",
    117: "stone_wall",
    155: "stone_wall",
    78: "gate",
    88: "gate",
    64: "gate",
    67: "gate",
    199: "fish_trap",
    276: "wonder",
    1021: "feitoria",
    1665: "donjon",
    1734: "folwark",
    1809: "mule_cart",
    1747: "caravanserai",
}

# Canonical Mapping for Technologies
TECH_ID_TO_CANONICAL: Dict[int, str] = {
    # Ages
    101: "feudal_age",
    102: "castle_age",
    103: "imperial_age",
    # Eco Technologies
    22: "loom",
    202: "double_bit_axe",
    203: "bow_saw",
    221: "two_man_saw",
    14: "horse_collar",
    13: "heavy_plow",
    12: "crop_rotation",
    55: "gold_mining",
    182: "gold_shaft_mining",
    278: "stone_mining",
    279: "stone_shaft_mining",
    213: "wheelbarrow",
    249: "hand_cart",
    8: "town_watch",
    280: "town_patrol",
    17: "coinage",
    23: "banking",
    15: "guilds",
    # Blacksmith Archer
    199: "fletching",
    200: "bodkin_arrow",
    201: "bracer",
    211: "padded_archer_armor",
    212: "leather_archer_armor",
    219: "ring_archer_armor",
    # Blacksmith Cavalry
    217: "scale_barding_armor",
    218: "chain_barding_armor",
    220: "plate_barding_armor",
    67: "forging",
    68: "iron_casting",
    75: "blast_furnace",
    # Blacksmith Infantry
    215: "scale_mail_armor",
    216: "chain_mail_armor",
    222: "plate_mail_armor",
    # Military Stable / Range / Barracks
    435: "bloodlines",
    39: "husbandry",
    93: "ballistics",
    437: "thumb_ring",
    436: "parthian_tactics",
    438: "supplies",
    215: "squires",
    214: "arson",
    65: "tracking",
    # University & Defense
    47: "chemistry",
    377: "siege_engineers",
    51: "treadmill_crane",
    50: "masonry",
    54: "architecture",
    63: "fortified_wall",
    64: "guard_tower_tech",
    140: "keep_tech",
    90: "bombard_tower_tech",
    379: "arrowslits",
    380: "murder_holes",
    194: "heated_shot",
    # Monastery
    252: "fervor",
    231: "sanctity",
    233: "redemption",
    230: "atonement",
    439: "herbal_medicine",
    236: "heresy",
    316: "illumination",
    319: "block_printing",
    440: "theocracy",
    315: "faith",
}

# Base Gathering Rates (resources per second per villager)
BASE_GATHER_RATES = {
    "food_berries": 0.31,
    "food_sheep": 0.33,
    "food_hunt": 0.41,
    "food_farm": 0.35,
    "wood": 0.39,
    "gold": 0.38,
    "stone": 0.36,
}

# Standard Unit Base Costs (Food, Wood, Gold, Stone)
UNIT_BASE_COSTS: Dict[str, Tuple[int, int, int, int]] = {
    "villager": (50, 0, 0, 0),
    "militiaman": (60, 0, 20, 0),
    "man_at_arms": (60, 0, 20, 0),
    "long_swordsman": (60, 0, 20, 0),
    "champion": (60, 0, 20, 0),
    "spearman": (35, 25, 0, 0),
    "pikeman": (35, 25, 0, 0),
    "halberdier": (35, 25, 0, 0),
    "eagle_scout": (20, 0, 50, 0),
    "eagle_warrior": (20, 0, 50, 0),
    "archer": (0, 25, 45, 0),
    "crossbowman": (0, 25, 45, 0),
    "arbalester": (0, 25, 45, 0),
    "skirmisher": (25, 35, 0, 0),
    "elite_skirmisher": (25, 35, 0, 0),
    "cavalry_archer": (0, 40, 60, 0),
    "heavy_cavalry_archer": (0, 40, 60, 0),
    "hand_cannoneer": (45, 0, 50, 0),
    "scout_cavalry": (80, 0, 0, 0),
    "light_cavalry": (80, 0, 0, 0),
    "hussar": (80, 0, 0, 0),
    "knight": (60, 0, 75, 0),
    "cavalier": (60, 0, 75, 0),
    "paladin": (60, 0, 75, 0),
    "camel_rider": (55, 0, 60, 0),
    "heavy_camel_rider": (55, 0, 60, 0),
    "battering_ram": (0, 160, 75, 0),
    "mangonel": (0, 160, 135, 0),
    "scorpion": (0, 75, 75, 0),
    "bombard_cannon": (0, 225, 225, 0),
    "monk": (0, 0, 100, 0),
    "trebuchet": (0, 200, 200, 0),
    "trade_cart": (0, 100, 50, 0),
    "fishing_ship": (0, 75, 0, 0),
}

# Building Costs (Food, Wood, Gold, Stone)
BUILDING_BASE_COSTS: Dict[str, Tuple[int, int, int, int]] = {
    "house": (0, 25, 0, 0),
    "mill": (0, 100, 0, 0),
    "farm": (0, 60, 0, 0),
    "lumber_camp": (0, 100, 0, 0),
    "mining_camp": (0, 100, 0, 0),
    "dock": (0, 150, 0, 0),
    "barracks": (0, 175, 0, 0),
    "archery_range": (0, 175, 0, 0),
    "stable": (0, 175, 0, 0),
    "blacksmith": (0, 150, 0, 0),
    "market": (0, 175, 0, 0),
    "monastery": (0, 175, 0, 0),
    "siege_workshop": (0, 200, 0, 0),
    "university": (0, 200, 0, 0),
    "town_center": (0, 275, 0, 100),
    "castle": (0, 0, 0, 650),
    "watch_tower": (0, 50, 0, 125),
    "outpost": (0, 25, 0, 5),
    "palisade_wall": (0, 2, 0, 0),
    "palisade_gate": (0, 20, 0, 0),
    "stone_wall": (0, 0, 0, 5),
    "gate": (0, 0, 0, 30),
}

# Line of Sight Radii (tiles)
LINE_OF_SIGHT_RADII: Dict[str, float] = {
    "scout_cavalry": 6.0,
    "light_cavalry": 8.0,
    "hussar": 10.0,
    "eagle_scout": 6.0,
    "villager": 4.0,
    "archer": 6.0,
    "crossbowman": 7.0,
    "arbalester": 7.0,
    "skirmisher": 6.0,
    "knight": 4.0,
    "cavalier": 4.0,
    "paladin": 5.0,
    "militiaman": 4.0,
    "spearman": 4.0,
    "monk": 11.0,
    "mangonel": 9.0,
    "scorpion": 9.0,
    "battering_ram": 3.0,
    "trebuchet": 19.0,
    "town_center": 8.0,
    "outpost": 10.0,
    "watch_tower": 10.0,
    "castle": 11.0,
    "house": 2.0,
    "barracks": 4.0,
    "archery_range": 4.0,
    "stable": 4.0,
    "siege_workshop": 4.0,
    "blacksmith": 4.0,
    "market": 4.0,
    "mill": 4.0,
    "lumber_camp": 4.0,
    "mining_camp": 4.0,
    "default_unit": 4.0,
    "default_building": 4.0,
}


def get_canonical_object_name(object_id: int, fallback: str = "unknown") -> str:
    """Resolve raw numeric object ID to canonical string name."""
    return OBJECT_ID_TO_CANONICAL.get(object_id, f"{fallback}_{object_id}")


def get_canonical_tech_name(tech_id: int, fallback: str = "unknown_tech") -> str:
    """Resolve raw numeric technology ID to canonical string name."""
    return TECH_ID_TO_CANONICAL.get(tech_id, f"{fallback}_{tech_id}")


def get_civ_name(civ_id: int) -> str:
    """Resolve raw civ ID to standard name."""
    return CIVILIZATIONS.get(civ_id, f"Unknown Civ ({civ_id})")
